### ISSUE TITLE
ACTION NEEDED: SIG for Oracle Cloud Provider

### ISSUE THREAD

**Issue by robzienert** [spinnaker/governance#127]
@shihchang @guoyongzhang

The Oracle cloud provider has been identified as not having a Special Interest Group created for it. A SIG must be formed for each Cloud Provider to offer the community a communications channel for feedback and support. Since there is not already a SIG formed for this cloud provider, one will need to be created.

With the creation of the SIG, adherence to the [Cloud Provider Requirements](https://github.com/spinnaker/governance/blob/master/cloud-provider-requirements.md) will be required. 

**If no action is taken on this issue by the 1st of June, 2020, this cloud provider will be a candidate for removal from the core Spinnaker project and may be moved to a plugin where it will need to be maintained separately.**

## Why was I assigned this issue?

We were unable to find a complete list of email address contacts for this cloud provider to contact the owners directly. Please copy any individuals that may be a better contact for fielding this issue if needed.

## What we need from you

A new SIG needs to be formed for this cloud provider. You can read about the process on forming a SIG following the directions on the [SIG Lifecycle](https://github.com/spinnaker/governance/blob/master/sig-lifecycle.md) page. 

If continued support of this cloud provider is not planned by your organization, please let us know so we may plan accordingly.

**Comment by robzienert** [comment]
The Oracle cloud provider has now been removed from the project. You may still submit a proposal for a SIG to restore the cloud provider.

**Comment by CyrusKOCI** [comment]
Hi @robzienert. I'm a summer intern at OCI and was interested in forming a SIG for further working on Spinnaker and OCI. Is there anything you need from my end to get the process started?

**Comment by plumpy** [comment]
Hi Cyrus, thanks for volunteering. As mentioned, the Oracle provider has been removed from Spinnaker builds. The last version of Spinnaker with Oracle Cloud support is 1.20.

You can create a SIG by [sending a PR adding your SIGs details to this repository](https://github.com/spinnaker/governance/blob/master/sig-lifecycle.md). (See the other SIGs for examples.) That said, we'd require a SIG sponsor that is going to be ongoing. Is there someone you're working with that can commit to continuing support of the Oracle code going forward? Since your employment there is temporary, we'd really want a full-time employee to commit to this work before we'd consider putting it back in the builds.

Thanks!

**Comment by raj-inamdar** [comment]
Hi @robzienert, Thanks for your your input. We will soon be submitting a SIG PR for supporting Oracle Cloud Driver by Oracle full time staff.
