### ISSUE TITLE
REQUEST: New Approver status for chinikins

### ISSUE THREAD

**Issue by Chinikins** [spinnaker/governance#156]
### Github Username

@chinikins

### Requirements

- [X] Belongs to an organization with significant stake in project
- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Is already fulfilling the Reviewer role
- [X] Has reviewed 5 PRs of significant scope
- [X] Sponsored by 2 Approvers

### Sponsors

- @kevinawoo 
- @dnilasor 
- @ezimanyi 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Cloudera
- Links to public Spinnaker PRs:
https://github.com/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3AChinikins+
- Looking to become a maintainer for the Spin CLI project and Sponnet library as well. I've reviewed some things in the sponnet library that have been hanging around for awhile that could some love and merges. A lot of times sponnet changes go hand in hand with Spin CLI changes.

**Comment by kevinawoo** [comment]
@Chinikins has been activity contributing to the [spinnaker/spin](https://github.com/spinnaker/spin/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3AChinikins+is%3Aclosed) and I think her PRs has been significant improvements and fixes to the `spin cli`. We've also been having conversations about how to improve testability of that codebase.

She's also been really active in the Spinnaker Gardening Days and also in Slack #general answering questions.

With all that evidence, I approve!

![](https://media.giphy.com/media/3o7qE7iHUUPHfV7xQI/giphy.gif)

**Comment by ezimanyi** [comment]
Definitely support reviewer status for @Chinikins based on the contributions to `spin`!

I would probably lean towards first granting reviewer status, then granting approver as a separate request after a few more significant PR reviews.  But I would support reasonably quickly moving from reviewer to approver once the required reviews are done.

In particular, definitely excited to have someone interested in maintaining spin and sponnet.  Based on the above PRs, I think having @Chinikins be a maintainer of these will be great for the project!

**Comment by ezimanyi** [comment]
So I guess formal vote:
+1 for reviewer status, both as a sponsor and as my TOC vte

**Comment by ethanfrogers** [comment]
Accidentally cleared the assignees some how 🤦. Sorry for any extraneous notifications!

**Comment by dnilasor** [comment]
Hi all, leaving my approval of @Chinikins as a sponsor here. She has clearly fulfilled the requirements for Reviewer status, so please grant it. Yayyy we're so happy to have you @Chinikins!!!

Regarding Approver status, @ezimanyi et al, can we be more specific with @Chinikins about the outstanding requirements to attain Approver status? I am asking on her behalf, but also in the interest of improving our governance documentation so that contributors can be motivated by clear and unbiased guidelines. 

I do see ["Is already fulfilling the Reviewer role" listed as a requirement for Approver status](https://github.com/spinnaker/governance/blob/master/governance.md#approvers), but I don't see a rule anywhere stating that contributors _must_ by officially granted a lower role before achieving a higher one. In this case, since the duties of "Reviewer" _are_ already being fulfilled, then by my reading, this requirement is satisfied already.

@ezimanyi, you stated that you will support Approver status "after a few more significant PR reviews" are completed. Can you provide more detail on what makes a PR review significant?

And, all, are there any other outstanding requirements for @Chinikins to meet?

**Comment by robzienert** [comment]
+1 for Reviewer status. @Chinikins is not presently a Reviewer, and it is currently a requirement towards becoming an Approver.

> I do see "Is already fulfilling the Reviewer role" listed as a requirement for Approver status, but I don't see a rule anywhere stating that contributors must be officially granted a less-responsible role before achieving a greater one. In this case, since the duties of "Reviewer" are already being fulfilled, then by my reading, this requirement is satisfied already.

The rule stating that contributors must be officially granted Reviewer to meet Approver requirements is in the requirements for Approver.

It's clear that the TOC needs to review the requirements for each role and make them more qualitative. We'll be taking time in our next sync to figure these things out, as well as improving the governance charter to be more explicit on the ladder, its progression and so-on, including potentially introducing new roles where it makes sense.

**Comment by plumpy** [comment]
TOC +1! Thanks for your work!

I sent an invite to join the organization and the `oss-reviewers` group. Let me know if you have any issues accepting it!

**Comment by ezimanyi** [comment]
Just to close the loop here on the questions above.

#### The approval process generally

I agree that "significant PR reviews" should be much better clarified or eliminated from our governance documentation.  I believe the original intent there was to avoid the edge case of someone submitting 5 PRs that make really minor changes (ex: updating a comment, doing a dependency bump that requires no further changes).  While of course these changes are valuable (and a great way to get involved!), I think we wanted to ensure that the nominee's contributions were a bit more involved.  Maybe we should just document a few examples of what shouldn't count and leave it at that.

Regarding "already fulfilling the reviewer role", this was added in #52 because we wanted people to first become a reviewer; as can be seen on the PR there was some confusion about whether you could then immediately become an approver after that but this was not resolved at the time.  I think we've always interpreted it as you need to first become a reviewer, then an approver, but I agree this is confusing and we should clarify it.

@robzienert has opened #157 to better clarify these roles, so we can avoid confusion like this going forward---any comments/thoughts are welcome/encouraged on that issue!

#### This particular request

In this case, when I reviewed the issue a couple of days ago, I used the [following query](https://github.com/pulls?q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3AChinikins+org%3Aspinnaker) to look for merged PRs that @Chinikins had reviewed, and found only 3 that at that time, so that requirement wasn't met regardless of the definition of what is significant.

Since that time the number of reviewed PRs has increased to 8, and @Chinikins has also shared with me some other reviews that don't technically show up but were done in comments/discussions:
* spinnaker/sponnet#7
* spinnaker/spin#263 (which ended up not getting merged because @Chinikins found a better way and implemented it)

Based on that I would vote to give @Chinikins approver status, as she meets the current requirements.  This would probably be one of the fastest transitions from reviewer -> approver that we've ever done since we implemented the process, but I think that the quality of @Chinikins contributions to spin/sponnet warrant this.

I think discussion of that should be moved to a new request for approver status, but I would vote to grant that status at this point.
